### ISSUE TITLE
Make a simple android app to test ADC communication via Bluetooth

### ISSUE THREAD

**Issue by GrazianoCapelli** [BasicAirData/AirDataComputer#45]
I propose to make a first android app (a simple **ADC Tester**), in order to:
- Verify and test the ADC communication protocol;
- Find possible bottlenecks and limits of the Bluetooth interface;
- Refine protocol, transmission methods, and connection setup in order to optimize the system;
- Find the best way to implement the communication on Android-side;
- (Last but not least) Give to all users a fast and simple way to test their own DIY units;

**Comment by JLJu** [comment]
That will be great! Not to say that this will be the first fully-fledged plug and play DIY solution :-). Of course, consider me on board. I can help with Android Apps. 
The basic test of libraries is proceeding and will end soon. Update of documentation is next to completion.

**Comment by GrazianoCapelli** [comment]
A small app has been committed (commit a30a686) in order to offer a fast way to test the device via Bluetooth. The app can connect / disconnect, send and receive messages, and presents the messages in a Terminal-like way.
This is obviously a first start point, it needs some (many) adjustments and refinements.

**Comment by JLJu** [comment]
A screen shot of ADCTester communicating with the ADC. By far the best! :-)
![screenshot_2017-05-09-23-26-39](https://cloud.githubusercontent.com/assets/16468586/25874447/e445319c-3512-11e7-9ee0-edc6c6f94882.png)
