### ISSUE TITLE
Altitude Wrong

### ISSUE THREAD

**Issue by BasicAirData** [BasicAirData/AirDataComputer#6]
ISAAltitude reported at 90000 Pa is more than 20000 m.

**Comment by Georacer** [comment]
Did it feel nice to close an issue once in a while?

**Comment by BasicAirData** [comment]
Walking on the moon :-)

**Comment by BasicAirData** [comment]
I love to watch a steady stream of data 
$1.084653,40.406101,40.406101,42.940750,42.940750,0.003990,288.149990,988.495000,0.000018,20456.428000
$100.000000,0.999994,0.050000,50.000000
$0.004168,1.010152,1.010152,1.077396,1.000000,0.900000
